Repository ha3158987/HayanMind_FE_assignment, pull requests merged in 2021-07, with the labels that each got.

#2 CRA 초기 환경세팅 완료
  .gitignore
  README.md
  package-lock.json
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/App.css
  src/App.js
  src/App.test.js
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: init

#4 Presentational & Container 으로 디렉토리 구조 변경
  src/components/Card/CardContainer.jsx
  src/components/Card/CardPresenter.jsx
  src/components/CardList/CardListContainer.jsx
  src/components/CardList/CardListPresenter.jsx
Labels: feat

#7 Card & CardList 컴포넌트 구현
  src/App.js
  src/components/Card/CardContainer.jsx
  src/components/Card/CardPresenter.jsx
  src/components/CardList/CardListContainer.jsx
  src/components/CardList/CardListPresenter.jsx
  src/components/util/mock.json
Labels: feat

#9 Component style 적용
  package-lock.json
  package.json
  src/components/CardList/CardListContainer.jsx
  src/components/CardList/CardListPresenter.jsx
  yarn.lock
Labels: style

#10 API util 생성 & API 데이터 적용
  src/components/CardList/CardListContainer.jsx
  src/components/util/API.js
Labels: feat

#11 폴더 구조 리팩토링
  src/components/CardList/CardListContainer.jsx
  src/components/util/mock.json
  src/util/API.js
Labels: refactor

#13 Component style 적용 추가
  src/components/Card/CardPresenter.jsx
  src/components/CardList/CardListPresenter.jsx
Labels: style

#14 infinite scroll 구현 완료
  src/components/Card/CardContainer.jsx
  src/components/Card/CardPresenter.jsx
  src/components/CardList/CardListContainer.jsx
  src/components/CardList/CardListPresenter.jsx
Labels: feat

#16 리드미 파일 업데이트
  README.md
Labels: docs

#18 전반적인 리팩토링 작업 완료
  src/components/Card/CardPresenter.jsx
  src/components/CardList/CardListContainer.jsx
  src/components/CardList/CardListPresenter.jsx
Labels: refactor
